# Tabla de multiplicar.
print("Enter the number of the multiplication table you want")
print("")
print("0")
print("1")
print("2")
print("3")
print("4")
print("5")
print("6")
print("7")
print("8")
print("9")
print("10")
print("")